const MAJOR_ARCANA = [
    { name: "The Fool", img: "https://i.imgur.com/IBrMUUS.png", def: "Innocence, new beginnings, free spirit. Step into the unknown with faith.", vibe: "sets a path of raw potential" },
    { name: "The Magician", img: "https://i.imgur.com/5PidMHl.png", def: "Manifestation, power, skill, action. You have all the tools to succeed.", vibe: "ignites your creative willpower" },
    { name: "The High Priestess", img: "https://i.imgur.com/xrsmWEA.png", def: "Intuition, sacred knowledge, mystery. Look within; the answers are in the silence.", vibe: "whispers secrets to your soul" },
    { name: "The Empress", img: "https://i.imgur.com/RvakGCX.png", def: "Femininity, abundance, nurturing, creation. Abundance is blooming around you.", vibe: "nurtures a harvest of success" },
    { name: "The Emperor", img: "https://i.imgur.com/K4oVvvj.png", def: "Authority, structure, stability, leadership. Establish your boundaries.", vibe: "demands sovereign control" },
    { name: "The Hierophant", img: "https://i.imgur.com/GRF1erw.png", def: "Tradition, spiritual wisdom, conformity. Seek counsel from established wisdom.", vibe: "anchors you to traditional wisdom" },
    { name: "The Lovers", img: "https://i.imgur.com/DVAdlIA.png", def: "Love, harmony, values alignment. A choice must be made from the heart.", vibe: "presents a crossroad of the heart" },
    { name: "The Chariot", img: "https://i.imgur.com/K5lk6Om.png", def: "Determination, control, ambition, victory. Drive forward with unwavering focus.", vibe: "propels you with divine momentum" },
    { name: "Strength", img: "https://i.imgur.com/WF9jYOf.png", def: "Courage, inner strength, compassion. Control your impulses with kindness.", vibe: "tames your shadows with grace" },
    { name: "The Hermit", img: "https://i.imgur.com/GgoMlM8.png", def: "Introspection, solitude, inner guidance. Withdraw from the noise to find your light.", vibe: "calls you into the sacred silence" },
    { name: "Wheel of Fortune", img: "https://i.imgur.com/oQ7dG8i.png", def: "Change, destiny, cycles. The wheel is turning; fate is in motion.", vibe: "spins a new thread of destiny" },
    { name: "Justice", img: "https://i.imgur.com/xxvbuEe.png", def: "Truth, fairness, accountability. A fair outcome is guaranteed by cosmic law.", vibe: "balances the scales of your karma" },
    { name: "The Hanged Man", img: "https://i.imgur.com/b71lXKz.png", def: "Surrender, new perspective, pause. Let go of the old to see the new.", vibe: "suspends time for a new vision" },
    { name: "Death", img: "https://i.imgur.com/WB1hQzH.png", def: "Endings, transformation, rebirth. Release the past; a new cycle begins.", vibe: "shatters the old for rebirth" },
    { name: "Temperance", img: "https://i.imgur.com/2rUNAHs.png", def: "Balance, moderation, harmony. Combine your forces to create peace.", vibe: "alchemizes your internal fire" },
    { name: "The Devil", img: "https://i.imgur.com/WA3Zekv.png", def: "Attachment, temptation, material focus. Beware of chains that bind you.", vibe: "exposes your self-made chains" },
    { name: "The Tower", img: "https://i.imgur.com/OGbBcsY.png", def: "Sudden change, upheaval, revelation. The false structures must fall.", vibe: "demolishes illusions instantly" },
    { name: "The Star", img: "https://i.imgur.com/zf2SNWL.png", def: "Hope, renewal, faith, healing. The spirits are guiding you to calm waters.", vibe: "pours starlight into your soul" },
    { name: "The Moon", img: "https://i.imgur.com/uaLXrGB.png", def: "Illusion, intuition, subconscious. Trust your gut instincts over appearances.", vibe: "reveals truth hidden in shadows" },
    { name: "The Sun", img: "https://i.imgur.com/FxEoqnn.png", def: "Joy, success, vitality, clarity. Total illumination and happiness follow you.", vibe: "radiates pure success and joy" },
    { name: "Judgement", img: "https://i.imgur.com/9E5aH31.png", def: "Awakening, renewal, decisiveness. You are called to your highest self.", vibe: "sounds the call for your rebirth" },
    { name: "The World", img: "https://i.imgur.com/XdoOTCP.png", def: "Completion, fulfillment, wholeness. The journey is complete; celebrate.", vibe: "closes the circle of fulfillment" }
];

const MINOR_ARCANA = [
    // WANDS
    { name: "Ace of Wands", def: "Inspiration, new opportunities, growth.", vibe: "ignites a fire of new ideas" },
    { name: "Two of Wands", def: "Planning, progress, decisions, discovery.", vibe: "opens doors to future planning" },
    { name: "Three of Wands", def: "Expansion, foresight, overseas opportunities.", vibe: "expands your horizon of success" },
    { name: "Four of Wands", def: "Celebration, harmony, homecoming, milestones.", vibe: "builds a foundation of joy" },
    { name: "Five of Wands", def: "Conflict, competition, tension.", vibe: "challenges you with necessary friction" },
    { name: "Six of Wands", def: "Victory, recognition, success, public praise.", vibe: "crowns you with public acclaim" },
    { name: "Seven of Wands", def: "Defense, perseverance, standing your ground.", vibe: "tests your courage under pressure" },
    { name: "Eight of Wands", def: "Speed, progress, swift action.", vibe: "moves your life at light speed" },
    { name: "Nine of Wands", def: "Resilience, persistence, boundaries.", vibe: "fortifies your final defense" },
    { name: "Ten of Wands", def: "Burden, responsibility, stress.", vibe: "weights your shoulders with duty" },
    { name: "Page of Wands", def: "Curiosity, enthusiasm, new ideas.", vibe: "brings a message of adventure" },
    { name: "Knight of Wands", def: "Bold action, passion, adventure.", vibe: "charges forward with intense heat" },
    { name: "Queen of Wands", def: "Confidence, charisma, creativity.", vibe: "radiates self-assured magnetic charm" },
    { name: "King of Wands", def: "Leadership, vision, authority.", vibe: "rules your path with creative fire" },
    // CUPS
    { name: "Ace of Cups", def: "New emotions, love, compassion, intuition.", vibe: "overflows your heart with love" },
    { name: "Two of Cups", def: "Partnership, mutual attraction, unity.", vibe: "bonds you in a divine union" },
    { name: "Three of Cups", def: "Celebration, friendship, community.", vibe: "links you to a circle of joy" },
    { name: "Four of Cups", def: "Apathy, contemplation, withdrawal.", vibe: "stagnates the emotional flow" },
    { name: "Five of Cups", def: "Loss, grief, regret, focus on disappointment.", vibe: "mourns the spilled water of the past" },
    { name: "Six of Cups", def: "Nostalgia, memories, past connections.", vibe: "revives the sweetness of memory" },
    { name: "Seven of Cups", def: "Illusion, choices, wishful thinking.", vibe: "distracts with a hallway of mirrors" },
    { name: "Eight of Cups", def: "Walking away, seeking meaning, growth.", vibe: "leads you to walk away from empty cups" },
    { name: "Nine of Cups", def: "Contentment, satisfaction, fulfillment.", vibe: "grants you a wish of the soul" },
    { name: "Ten of Cups", def: "Harmony, emotional completion, happiness.", vibe: "completes your emotional world" },
    { name: "Page of Cups", def: "Emotional curiosity, creativity.", vibe: "delivers a message of feeling" },
    { name: "Knight of Cups", def: "Romance, charm, emotional pursuit.", vibe: "serenades you with romantic intent" },
    { name: "Queen of Cups", def: "Compassion, intuition, depth, care.", vibe: "nurtures you with psychic depth" },
    { name: "King of Cups", def: "Emotional balance, calm, wisdom.", vibe: "masters the tides of your emotion" },
    // SWORDS
    { name: "Ace of Swords", def: "Clarity, truth, breakthrough, logic.", vibe: "cuts through the fog of doubt" },
    { name: "Two of Swords", def: "Indecision, stalemate, emotional block.", vibe: "freezes your path in dual thought" },
    { name: "Three of Swords", def: "Heartbreak, sorrow, painful truth.", vibe: "pierces the heart with hard truth" },
    { name: "Four of Swords", def: "Rest, recovery, pause, restoration.", vibe: "demands a sanctuary for the mind" },
    { name: "Five of Swords", def: "Conflict, betrayal, hollow victory.", vibe: "leaves a bitter taste of ego battle" },
    { name: "Six of Swords", def: "Transition, healing, moving on.", vibe: "steers you toward calmer waters" },
    { name: "Seven of Swords", def: "Deception, strategy, secrecy.", vibe: "shadows the path with hidden motives" },
    { name: "Eight of Swords", def: "Restriction, anxiety, fear.", vibe: "traps the soul in mental cages" },
    { name: "Nine of Swords", def: "Anxiety, nightmares, guilt.", vibe: "torments the night with worry" },
    { name: "Ten of Swords", def: "Painful ending, collapse, finality.", vibe: "strikes the final blow to the old" },
    { name: "Page of Swords", def: "Curiosity, communication, agility.", vibe: "spies the truth with a sharp mind" },
    { name: "Knight of Swords", def: "Ambition, direct action, urgency.", vibe: "rushes in with intellectual fury" },
    { name: "Queen of Swords", def: "Clarity, honesty, sharp intellect.", vibe: "judges the situation with cold logic" },
    { name: "King of Swords", def: "Authority, logic, ethical leadership.", vibe: "decrees the law of the mind" },
    // PENTACLES
    { name: "Ace of Pentacles", def: "New financial opportunity, prosperity.", vibe: "plants the seed of wealth" },
    { name: "Two of Pentacles", def: "Balance, adaptability, priorities.", vibe: "juggles the coins of your material world" },
    { name: "Three of Pentacles", def: "Teamwork, collaboration, skill.", vibe: "constructs a monument of work" },
    { name: "Four of Pentacles", def: "Saving, security, control.", vibe: "grips tight to the earthly treasures" },
    { name: "Five of Pentacles", def: "Hardship, financial loss, isolation.", vibe: "tests the soul through material lack" },
    { name: "Six of Pentacles", def: "Generosity, giving and receiving.", vibe: "balances the exchange of resources" },
    { name: "Seven of Pentacles", def: "Patience, assessment, progress.", vibe: "watches the garden of your effort grow" },
    { name: "Eight of Pentacles", def: "Apprenticeship, diligence, quality.", vibe: "hones the craft of your daily hustle" },
    { name: "Nine of Pentacles", def: "Independence, luxury, sufficiency.", vibe: "surrounds you with self-made luxury" },
    { name: "Ten of Pentacles", def: "Legacy, family wealth, security.", vibe: "secures the lineage of your fortune" },
    { name: "Page of Pentacles", def: "New study, practical plan, ambition.", vibe: "presents a new manifest opportunity" },
    { name: "Knight of Pentacles", def: "Reliability, hard work, routine.", vibe: "plows the field of steady success" },
    { name: "Queen of Pentacles", def: "Nurturing, practicality, comfort.", vibe: "grounded queen of the physical realm" },
    { name: "King of Pentacles", def: "Wealth, stability, leadership.", vibe: "masters the realm of material wealth" }
];
